---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
spec:
  selector:
    name: nginx  # Replace 'app' with the label of your target pod
  ports:
    - protocol: TCP
      port: 8080    # Port on the service
      targetPort: 443  # Port on the pod
  type: ClusterIP
