---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  type: NodePort
  ports:
    - port: 80        # Port to expose on the service
      targetPort: 443  # Port to forward traffic to on the pods
      nodePort: 30080 # Port accessible externally on each node
  selector:
    name: nginx       # Select pods with label "app=my-app"

